DROP TABLE CMNT03_STATION_GRID;

CREATE TABLE CMNT03_STATION_GRID(
STAT_ID CHAR(8) REFERENCES MSTT02_STATION(STAT_ID),
PONT_X_FROM INTEGER(6),
PONT_Y_FROM INTEGER(6),
PONT_X_TO INTEGER(6),
PONT_Y_TO INTEGER(6)
);