DROP TABLE INFT05_LINE_KNOWLEDGE;

CREATE TABLE INFT05_LINE_KNOWLEDGE(
LINE_KNOW_ID CHAR(5) PRIMARY KEY,
LINE_ID CHAR(6) NOT NULL,
LINE_NAME NVARCHAR(50),
LINE_KNOW_TITLE NVARCHAR(100),
LINE_KNOW_CONTENT NVARCHAR(500),
READ_FLAG CHAR(1),
READ_TIME CHAR(14),
FAVO_FLAG CHAR(1),
FAVO_TIME CHAR(14)
);