DROP TABLE INFT01_STRATEGY;

CREATE TABLE INFT01_STRATEGY(
STRA_ID CHAR(6) PRIMARY KEY,	
STRA_THEME NVARCHAR(50),
SPPL_PEOPLE NVARCHAR(50) ,
STRA_SEASON NVARCHAR(50),
STRA_DESCRIPTION NVARCHAR(2000),
READ_FLAG CHAR(1),
READ_TIME CHAR(14),
FAVO_FLAG CHAR(1),
FAVO_TIME CHAR(14)
);