DELETE FROM INFT05_LINE_KNOWLEDGE WHERE 1=1;

INSERT INTO INFT05_LINE_KNOWLEDGE
 (LINE_KNOW_ID,LINE_ID,LINE_NAME,LINE_KNOW_TITLE,LINE_KNOW_CONTENT,READ_FLAG,READ_TIME,FAVO_FLAG,FAVO_TIME)
 VALUES
('1','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('2','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('3','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('4','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('5','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('6','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('78','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('8','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('10','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('9','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('11','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('60','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('50','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
