DROP TABLE INFT03_RESCURE;

CREATE TABLE INFT03_RESCURE(
RESC_ID CHAR(5) PRIMARY KEY,
RESC_LOCA NVARCHAR(50) NOT NULL,
RESC_TYPE NVARCHAR(30),
RESC_CONTENT_CN NVARCHAR(500),
RESC_CONTENT_JP NVARCHAR(500),
READ_FLAG CHAR(1),
READ_TIME CHAR(14),
FAVO_FLAG CHAR(1),
FAVO_TIME CHAR(14)
);