DROP TABLE LINT01_TRAIN_SCHEDULE;

CREATE TABLE LINT01_TRAIN_SCHEDULE(
LINE_ID	CHAR(6) NOT NULL,
STAT_ID CHAR(8) NOT NULL,
DIRT_STAT_ID CHAR(8) NOT NULL,
DEST_STAT_ID CHAR(8) NOT NULL,
SCHE_TYPE CHAR(1),
DEPA_TIME CHAR(4),
TRAN_TYPE CHAR(2),
FIRST_TRAIN_FLAG CHAR(1)
);