DROP TABLE LINT04_ROUTE;

CREATE TABLE LINT04_ROUTE(
RUTE_ID CHAR(10) PRIMARY KEY,
START_STAT_ID CHAR(8),
TERM_STAT_ID CHAR(8)
);


--CREATE INDEX IDX_LINT04_ROUTE_START_STAT_ID ON LINT04_ROUTE (START_STAT_ID);
--CREATE INDEX IDX_LINT04_ROUTE_TERM_STAT_ID ON LINT04_ROUTE (TERM_STAT_ID);
CREATE INDEX IDX_LINT04_ROUTE ON LINT04_ROUTE (START_STAT_ID,TERM_STAT_ID);