DROP TABLE LINT05_ROUTE_DETAIL;

CREATE TABLE LINT05_ROUTE_DETAIL(
RUTE_ID CHAR(10) PRIMARY KEY,
RUTE_GROUP_ID CHAR(2) NOT NULL,
EXCH_STAT_ID CHAR(8) NOT NULL,
EXCH_LINE_ID CHAR(6) NOT NULL,
EXCH_DEST_ID CHAR(8) NOT NULL,
EXCH_TYPE CHAR(1),
EXCH_SEQ INTEGER(4),
MOVE_TIME INTEGER(4),
WAIT_TIME INTEGER(4)
);