DROP VIEW MSTV01_STATION_GROUP;

CREATE VIEW MSTV01_STATION_GROUP AS 
SELECT T1.STAT_ID,
T1.STAT_GROUP_ID, 
T2.LINE_ID,
T2.STAT_SEQ,
T2.STAT_METRO_ID,
T2.STAT_METRO_ID_FULL,
T2.STAT_NAME,
T2.STAT_NAME_KANA,
T2.STAT_NAME_ROME,
T2.STAT_NAME_EXT1,
T2.STAT_NAME_EXT2,
T2.STAT_NAME_EXT3,
T2.STAT_NAME_EXT4,
T2.STAT_NAME_EXT5,
T2.STAT_NAME_EXT6,
T2.STAT_LON,
T2.STAT_LAT,
T2.STAT_PREF,
T2.STAT_ADDR,
T2.STAT_DESP
FROM MSTT02_STATION AS T1 
JOIN MSTT02_STATION AS T2
ON T1.STAT_GROUP_ID = T2.STAT_GROUP_ID;
