DELETE FROM STAT02_COMERCIAL_NEARBY WHERE 1=1;

INSERT INTO STAT02_COMERCIAL_NEARBY
 (LMAK_ID,STAT_EXIT_ID,FAVO_FLAG,FAVO_TIME)
VALUES
('1',NULL,NULL,NULL)
,('2',NULL,NULL,NULL)
,('3',NULL,NULL,NULL)
,('4',NULL,NULL,NULL)
,('5',NULL,NULL,NULL)
;