DELETE FROM STAT04_FACILITY WHERE 1=1;

INSERT INTO STAT04_FACILITY
(FACI_ID,LINE_ID,STAT_ID,FACI_TYPE,FACI_NAME,FACI_DESP,FACI_LOCL,ESCA_DIRT,WHEL_CAIR_ACES,BABY_CAIR,BABY_CHGN_TABL,TOIL_FOR_OSTM)
VALUES
('1','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('2','2','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('3','3','3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('4','4','4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('5','5','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('6','6','6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('7','7','7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('8','8','8',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('9','9','9',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('10','10','10',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('11','11','11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('12','12','12',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('13','13','13',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
