DROP TABLE STAT01_STATION_EXIT;

CREATE TABLE STAT01_STATION_EXIT(
STAT_EXIT_ID CHAR(10) PRIMARY KEY,
STAT_ID CHAR(8) NOT NULL,
STAT_EXIT_NUM NVARCHAR(6) NOT NULL,
STAT_EXIT_NAME NVARCHAR(100) NOT NULL,
STAT_EXIT_TYPE INTEGER(1),
STAT_EXIT_LON DECIMAL(18,10),
STAT_EXIT_LAT DECIMAL(18,10),
STAT_EXIT_FLOOR INTEGER(2)
);