DELETE FROM STAT01_STATION_EXIT WHERE 1=1;

INSERT INTO STAT01_STATION_EXIT
 (STAT_EXIT_ID,LINE_ID,STAT_ID,STAT_EXIT_NUM,STAT_EXIT_NAME,STAT_EXIT_TYPE,STAT_EXIT_LON,STAT_EXIT_LAT,STAT_EXIT_FLOOR)
VALUES
('1','1','1','1','1',NULL,NULL,NULL,NULL)
,('2','2','2','2','2',NULL,NULL,NULL,NULL)
,('3','3','3','3','3',NULL,NULL,NULL,NULL)
,('4','4','4','4','4',NULL,NULL,NULL,NULL)
,('5','5','5','5','5',NULL,NULL,NULL,NULL);