DROP TABLE USRT02_TRAIN_ALARM;

CREATE TABLE USRT02_TRAIN_ALARM(
TRAI_ALAM_ID CHAR(5) PRIMARY KEY,
LINE_ID CHAR(6) NOT NULL,
STAT_ID CHAR(8) NOT NULL,
ALAM_TYPE CHAR(1),
ALAM_TIME CHAR(4),
TRAI_DIRT CHAR(8),
ALAM_FLAG CHAR(1),
BEEP_FLAG CHAR(1),
VOLE_FLAG CHAR(1),
ALARM_TIME DECIMAL(6,0),
SAVE_TIME CHAR(14)
);