DROP TABLE USRT02_TRAIN_ALARM;

CREATE TABLE USRT02_TRAIN_ALARM(
TRAI_ALAM_ID CHAR(5) PRIMARY KEY,
LINE_ID CHAR(6) NOT NULL,
LINE_NAME_LOCL NVARCHAR(100),
STAT_ID CHAR(8) NOT NULL,
STAT_NAME_LOCL NVARCHAR(100),
FIRST_TIME CHAR(14),
LAST_TIME CHAR(14),
FIRST_FLAG CHAR(1),
LAST_FLAG CHAR(1),
BEEP_FLAG CHAR(1),
VOLE_FLAG CHAR(1),
ALARM_TIME DECIMAL(6,0),
SAVE_TIME CHAR(14)
);