DELETE FROM USRT02_TRAIN_ALARM WHERE 1=1;

INSERT INTO USRT02_TRAIN_ALARM
 (TRAI_ALAM_ID,LINE_ID,LINE_NAME_LOCL,STAT_ID,STAT_NAME_LOCL,FIRST_TIME,LAST_TIME,FIRST_FLAG,LAST_FLAG,BEEP_FLAG,VOLE_FLAG,ALARM_TIME,SAVE_TIME)
VALUES
('1','1',NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('2','2',NULL,'2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('3','3',NULL,'3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('4','4',NULL,'4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('5','5',NULL,'5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('6','6',NULL,'6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('7','7',NULL,'7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('8','8',NULL,'8',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('9','9',NULL,'9',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('10','10',NULL,'10',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('11','11',NULL,'11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('12','12',NULL,'12',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('13','13',NULL,'13',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
