DELETE FROM LINT05_ROUTE_DETAIL WHERE 1=1;

INSERT INTO LINT05_ROUTE_DETAIL
 (RUTE_ID,RUTE_GROUP_ID,EXCH_STAT_ID,EXCH_LINE_ID,EXCH_DEST_ID,EXCH_TYPE,EXCH_SEQ,MOVE_TIME,WAIT_TIME)
VALUES
('1','1','1','1','1',NULL,NULL,NULL,NULL)
,('2','2','2','2','2',NULL,NULL,NULL,NULL)
,('3','3','3','3','3',NULL,NULL,NULL,NULL)
,('4','4','4','4','4',NULL,NULL,NULL,NULL)
,('5','5','5','5','5',NULL,NULL,NULL,NULL)
;

