DELETE FROM LINT01_TRAIN_SCHEDULE WHERE 1=1;

INSERT INTO LINT01_TRAIN_SCHEDULE
 (LINE_ID,STAT_ID,DIRT_STAT_ID,DEST_STAT_ID,SCHE_TYPE,DEPA_TIME,TRAN_TYPE,FIRST_TRAIN_FLAG)
VALUES
('1','1','1','1',NULL,NULL,NULL,NULL)
,('2','2','2','2',NULL,NULL,NULL,NULL)
,('3','3','3','3',NULL,NULL,NULL,NULL)
,('4','4','4','4',NULL,NULL,NULL,NULL)
,('5','5','5','5',NULL,NULL,NULL,NULL)
;

