DROP TABLE MSTT01_LINE;

CREATE TABLE MSTT01_LINE(
LINE_ID	CHAR(6) PRIMARY KEY,
STAT_ID CHAR(8) NOT NULL,
DIRT_STAT_ID CHAR(8) NOT NULL,
DEST_STAT_ID CHAR(8) NOT NULL,
SCHE_TYPE CHAR(1),
DEPA_TIME CHAR(4),
TRAN_TYPE CHAR(2),
FIRST_TRAIN_FLAG CHAR(1)
);