DELETE FROM LINT03_TRAIN_MOVING WHERE 1=1;

INSERT INTO LINT03_TRAIN_MOVING
 (LINE_ID,LINE_NAME,TIME_MOVING,TIME_VALID,MOVING_INFO,UPDATE_TIME)
VALUES
('1',NULL,NULL,NULL,NULL,NULL)
,('2',NULL,NULL,NULL,NULL,NULL)
,('3',NULL,NULL,NULL,NULL,NULL)
,('4',NULL,NULL,NULL,NULL,NULL)
,('5',NULL,NULL,NULL,NULL,NULL)
;

