DELETE FROM MSTT04_LANDMARK WHERE 1=1;

INSERT INTO MSTT04_LANDMARK
 (LMAK_ID,LMAK_NAME,LMAK_NAME_KANA,LMAK_NAME_ROME,LMAK_NAME_EXT1,LMAK_NAME_EXT2,LMAK_NAME_EXT3,LMAK_NAME_EXT4,LMAK_NAME_EXT5,LMAK_NAME_EXT6,LMAK_TYPE,LMAK_SUB_TYPE,LINE_ID,STAT_ID,STAT_EXIT_ID,LMAK_AVAL_TIME,LMAK_TICT_PRIC,LMAK_ADDR,LMAK_DESP,OLIMPIC_FLAG,EXIT_FLAG1,EXIT_FLAG2,EXIT_FLAG3,EXIT_FLAG4,IMAG_ID1,IMAG_ID2,IMAG_ID3,IMAG_ID4,IMAG_ID5,READ_FLAG,READ_TIME,FAVO_FLAG,FAVO_TIME)
VALUES
('1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,'1',NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2',NULL,'2',NULL,'2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'3',NULL,'3',NULL,'3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'4',NULL,'4',NULL,'4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'5',NULL,'5',NULL,'5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
;

