DELETE FROM USRT03_FAVORITE WHERE 1=1;

INSERT INTO USRT03_FAVORITE
 (FAVO_TYPE,FAVO_TIME,LINE_ID,STAT_ID,STAT_EXIT_ID,LMAK_ID,RUTE_ID,EXT1,EXT2,EXT3,EXT4,EXT5)
VALUES
('1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('2','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('3','3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('4','4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('5','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
;

