DROP TABLE INFT02_TIPS;

CREATE TABLE INFT02_TIPS(
TIPS_ID CHAR(5) PRIMARY KEY,
TIPS_TYPE NVARCHAR(30) NOT NULL,
TIPS_SUB_TYPE NVARCHAR(30),
TIPS_TITLE NVARCHAR(100) ,
TIPS_CONTENT NVARCHAR(500),
READ_FLAG CHAR(1),
READ_TIME CHAR(14),
FAVO_FLAG CHAR(1),
FAVO_TIME CHAR(14)
);