DELETE FROM INFT04_STAT_KNOWLEDGE WHERE 1=1;

INSERT INTO INFT04_STAT_KNOWLEDGE
 (STAT_KNOW_ID,LINE_ID,STAT_ID,LINE_NAME,STAT_NAME,STAT_KNOW_TITLE,STAT_KNOW_CONTENT,READ_FLAG,READ_TIME,FAVO_FLAG ,FAVO_TIME)
VALUES
('1','1','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('2','2','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('3','3','3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('4','4','4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('5','5','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('6','6','6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('7','7','7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('8','8','8',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('9','9','9',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('10','10','10',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('11','11','11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('12','12','12',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('13','13','13',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
