DROP TABLE INFT04_STAT_KNOWLEDGE;

CREATE TABLE INFT04_STAT_KNOWLEDGE(
STAT_KNOW_ID CHAR(5) PRIMARY KEY,
LINE_ID CHAR(6) NOT NULL,
STAT_ID CHAR(8) NOT NULL,
LINE_NAME NVARCHAR(50),
STAT_NAME NVARCHAR(50),
STAT_KNOW_TITLE NVARCHAR(100),
STAT_KNOW_CONTENT NVARCHAR(500),
READ_FLAG CHAR(1),
READ_TIME CHAR(14),
FAVO_FLAG CHAR(1),
FAVO_TIME CHAR(14)
);