DELETE FROM INFT03_RESCURE WHERE 1=1;

INSERT INTO INFT03_RESCURE
 (RESC_ID,RESC_LOCA,RESC_TYPE,RESC_CONTENT_CN,RESC_CONTENT_JP,READ_FLAG,FAVO_FLAG,FAVO_TIME)
 VALUES
('1','55',NULL,NULL,NULL,NULL,NULL,NULL)
,('2','55',NULL,NULL,NULL,NULL,NULL,NULL)
,('3','5',NULL,NULL,NULL,NULL,NULL,NULL)
,('4','5',NULL,NULL,NULL,NULL,NULL,NULL)
,('5','5',NULL,NULL,NULL,NULL,NULL,NULL)
,('6','5',NULL,NULL,NULL,NULL,NULL,NULL)
,('7','5',NULL,NULL,NULL,NULL,NULL,NULL)
,('8','5',NULL,NULL,NULL,NULL,NULL,NULL)
,('9','5',NULL,NULL,NULL,NULL,NULL,NULL)
,('10','5',NULL,NULL,NULL,NULL,NULL,NULL)
,('11','5',NULL,NULL,NULL,NULL,NULL,NULL)
,('12','5',NULL,NULL,NULL,NULL,NULL,NULL)
,('13','5',NULL,NULL,NULL,NULL,NULL,NULL);
