DELETE FROM USRT01_ARRIVAL_ALARM WHERE 1=1;


INSERT INTO USRT01_ARRIVAL_ALARM
 (ARRI_ALAM_ID,LINE_FROM_ID,LINE_FROM_NAME_LOCL,STAT_FROM_ID,STAT_FROM_NAME_LOCL,LINE_TO_ID,LINE_TO_NAME_LOCL,STAT_TO_ID,STAT_TO_NAME_LOCL,BEEP_FLAG,VOLE_FLAG,COST_TIME,ALARM_TIME,SAVE_TIME,ONBOARD_TIME,CANCEL_FLAG,CANCEL_TIME)
VALUES
('1','1',NULL,'1',NULL,'1',NULL,'1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('2','2',NULL,'2',NULL,'2',NULL,'2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('3','3',NULL,'3',NULL,'3',NULL,'3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('4','4',NULL,'4',NULL,'4',NULL,'4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('5','5',NULL,'5',NULL,'5',NULL,'5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('6','6',NULL,'6',NULL,'6',NULL,'6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('7','7',NULL,'7',NULL,'7',NULL,'7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('8','8',NULL,'8',NULL,'8',NULL,'8',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('9','9',NULL,'9',NULL,'9',NULL,'9',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('10','10',NULL,'10',NULL,'10',NULL,'10',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('11','11',NULL,'11',NULL,'11',NULL,'11',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('12','12',NULL,'12',NULL,'12',NULL,'12',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,('13','13',NULL,'13',NULL,'13',NULL,'13',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
